### ISSUE TITLE
Failure in "Add GPFS Dependent License RPMs"  for Data Access Edition

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-install-infra#113]
I've verified that on this same environment the Data Management Edition doesn't hit this error.  

Running the following on RHEL 7.7 (with 7.8 kernel) on x86_64 failed with Data_Access Edition.  I have the following changes in my playbook.yml file 

```
# grep 5.0 playbook.yml
    - scale_version: 5.0.5.0
    - scale_install_localpkg_path: /root/install-infra/Spectrum_Scale_Data_Access-5.0.5.0-x86_64-Linux-install
```

```
TASK [core/node : install | Add GPFS License RPMs to list] *********************************************************************************
ok: [PR-test-x-master] => (item=gpfs.license.da-5.0.5-0.x86_64.rpm)
ok: [PR-test-x-worker1] => (item=gpfs.license.da-5.0.5-0.x86_64.rpm)
ok: [PR-test-x-worker2] => (item=gpfs.license.da-5.0.5-0.x86_64.rpm)

TASK [core/node : install | Add GPFS Dependent License RPMs to list] ***********************************************************************
fatal: [PR-test-x-master]: FAILED! => {"msg": "list object has no element 0"}
fatal: [PR-test-x-worker1]: FAILED! => {"msg": "list object has no element 0"}
fatal: [PR-test-x-worker2]: FAILED! => {"msg": "list object has no element 0"}

PLAY RECAP 
...
...
```

I took a quick look at the task here and it seems like something is wrong.  In order to debug this, I had to add some debug print outs..  but i think this task block is not right.  https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/dev/roles/core/node/tasks/install_license_pkg.yml#L71

The two comments I have here: 
1. is line 73 even needed, it doesn't seem like it's used anywhere..  maybe later on? 
2. `scale_install_gpfs_adv` and `scale_install_gpfs_crypto` when installing Data Access are not defined here, so `files.0` has no element, and thus failure.  When running with Data Management it works.

**Comment by rajan-mis** [comment]
@vhu we already have a defect for DAE issue and i already fixed it but not yet merged . we have to  skip crypto and advance package installation similar as standard package because DAE package does contain advance and crypto functionality.

https://github.com/IBM/ibm-spectrum-scale-install-infra/issues/92
