### ISSUE TITLE
README should get updated with new inventory method for NSD's and filesystem(we need to use  `group_vars/all` instead of  `host_vars`  inventory  file   to create NSDs and file systems. )

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#17]
This issue will be applicable once latest code will get moved from `dev` to `master` branch.

**Comment by acch** [comment]
Hi @rajan-mis, this seems to be an older one. Is it still relevant?

If it it, can you provide some more explanation of what you want me to add to the README?

Thanks!
