### ISSUE TITLE
Collision with role names in default namespace

### ISSUE THREAD

**Issue by acch** [IBM/ibm-spectrum-scale-install-infra#189]
When running this role against my test environment I got the following error:

```
The conditional check 'scale_daemon_running | bool' failed.
The error was: error while evaluating conditional (scale_daemon_running | bool): 'scale_daemon_running' is undefined

The error appears to be in '.../ibm-spectrum-scale-install-infra/roles/core/node/tasks/install.yml': line 80, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# - include_tasks: update.yml
- include_tasks: upgrade.yml
  ^ here
```

When investigating this error I found that the `core/common` role didn't actually run, even though it's listed as a dependency:

```yaml
# roles/core/node/meta/main.yml
...
dependencies:
 - common
...
```

The root cause of the problem turned out to be the following: I have my own, custom role named `common`, which runs *before* the spectrum-scale-install-infra roles. Hence, when running the `core/node` role, Ansible checks the listed dependencies and detects that a role with that name was already run. It does not distinguish between my own role `common` and the role in `ibm-spectrum-scale-install-infra/roles/core/common`...

I resolved the error by simply renaming my own role.

My understanding is that **namespaces** are the aprropriate method for preventing these type of errors. I'd suggest to move all roles of this project into a dedicated namespace - e.g. `ibm.scale_core_common`, `ibm.scale_core_node`, etc. This would prevent name collisions in the default namespace.

I understand that the roles of this project aren't published to Ansible Galaxy, yet. However, I'd suggest to align with and follow the Galaxy recommendations regarding namespaces:
https://galaxy.ansible.com/docs/contributing/namespaces.html

> Ansible roles and collections are associated with a Galaxy namespace. In other words, a role is imported into a namespace, and a collection is uploaded or published to a namespace. When referencing a role or collection for download and install the namespace becomes part of the reference in the form `namespace.[role | collection]_name`.

**Comment by olemyk** [comment]
Hit the same issue here.

**Comment by acch** [comment]
Replaced by #247, so I'm closing this one...
