### ISSUE TITLE
Callhome - Role improvements. 

### ISSUE THREAD

**Issue by olemyk** [IBM/ibm-spectrum-scale-install-infra#196]
1. **Readme**
  Readme in Call home folder doesn't show the values, should be copied from main readme.md
 And the Readme is some difficult to read, so some improvement should be great.

2. **Default repo** is: http://9.11.84.162/gpfs_rpms/
File: roles/ibm-spectrum-scale-install-infra/roles/callhome/node/defaults/main.yml
value: `scale_install_callhome_repository_url: http://9.11.84.162/gpfs_rpms/`

3. **MM Commands** is not using full path.  
   In the other roles we are using full path `/usr/lpp/mmfs/bin/` for the mm command, but not in this role. 
   Maybe this should be changed to consistent?

4. **YUM REPO Description** is Zimon in Callhome
file: roles/ibm-spectrum-scale-install-infra/roles/callhome/node/tasks/install_repository.yml
`description: IBM Spectrum Scale (ZIMon)`

5.  **Callhome values**: 
If I use NO on Customer_country, ansible is reading it as false.  
Maybe we should make the examples with  ' '
```
      callhome_params:
       is_enabled: true
       customer_name: abc
       customer_email: abc@abc.com
       customer_id: 12345
      customer_country: 'NO'
```

6.  **Check if callhome group is already created**
Would be great not to have Ignore errors:

`TASK [ibm-spectrum-scale-install-infra/roles/callhome/cluster : configure | Check if callhome group is already created] *****************************************************************************************************************************************************************************************************************************
task path: /Users/olemyk/IdeaProjects/ansible-sandbox/roles/ibm-spectrum-scale-install-infra/roles/callhome/cluster/tasks/configure.yml:50
fatal: [scale-dev-01]: FAILED! => {"changed": true, "cmd": "mmcallhome group list", "delta": "0:00:00.044709", "end": "2020-08-12 13:38:56.450748", "msg": "non-zero return code", "rc": 1, "start": "2020-08-12 13:38:56.406039", "stderr": "No callhome group defined.", "stderr_lines": ["No callhome group defined."], "stdout": "", "stdout_lines": []}
...ignoring
`

**Comment by acch** [comment]
Totally agree with these suggestions.

**Comment by rajan-mis** [comment]
@olemyk Please let me know if you want to fix this issue. Thanks

**Comment by olemyk** [comment]
Looks like you have fixed this @rajan-mis  and much more. 

1. This only the case for users in Norway, NO.   This could be Updated in sample vars/callhome_vars.yml
2 - Default repo is removed.
3. - MM Commands: Using: "{{ scale_command_path }}mmcallhome 
4. - YUM REPO Description is Zimon in Callhome: Fixed and more.


Close This? @rajan-mis @acch
