### ISSUE TITLE
Improvements - Common Variable install_common_repository_url

### ISSUE THREAD

**Issue by olemyk** [IBM/ibm-spectrum-scale-install-infra#198]
When we are adding more and more of the roles, we need to specify the different `install_repository_url`. 

Would it be possible to Introduce a variable `scale_install_common_repository_url `and then derive the subdirectories automatically?  

it´s only the zimon,smb,ganesha,object that needs to specify the OS version: rhel7, rhel8 and sles12, sles15

Could it be set with set_fact: ?

- name:
  set_fact:
    scale_install_gpfs_rpms_repository_url: {{ scale_install_common_repository_url }}/...
    scale_install_gui_repository_url: {{ scale_install_common_repository_url }}/...
    scale_install_zimon_repository_url: {{ scale_install_common_repository_url }}/...
  when: scale_install_common_repository_url is defined    

```
   - scale_install_repository_url: "http://10.33.3.56/mrepo/scale/{{ scale_version }}/gpfs_rpms"
    - scale_install_zimon_repository_url: http://10.33.3.56/mrepo/scale/{{ scale_version }}/zimon_rpms/{{ scale_os }}
    - scale_install_gui_repository_url: http://10.33.3.56/mrepo/scale/{{ scale_version }}/gpfs_rpms
    - scale_install_callhome_repository_url: http://10.33.3.56/mrepo/scale/{{ scale_version }}/gpfs_rpms
```

``` from my old CES role. 
## Specify the URL of the (existing) Spectrum Scale Ganesha YUM repository
## (copy the contents of /usr/lpp/mmfs/.../ganesha_rpms/rhel7 to build your repository)
scale_install_ganesha_repository_url: "{{ scale_install_ces_repository_url }}/ganesha_rpms/{{ scale_os }}"
## Specify the URL of the (existing) Spectrum Scale Object YUM repository
## (copy the contents of /usr/lpp/mmfs/.../object_rpms/rhel7 to build your repository)
scale_install_object_repository_url: "{{ scale_install_ces_repository_url }}/object_rpms/{{ scale_os }}"
## Specify the URL of the (existing) Spectrum Scale Samba YUM repository
## (copy the contents of /usr/lpp/mmfs/.../smb_rpms/rhel7 to build your repository)
scale_install_samba_repository_url: "{{ scale_install_ces_repository_url }}/smb_rpms/{{ scale_os }}"

``

**Comment by acch** [comment]
I like the idea. Having a single variable `scale_install_common_repository_url` would make it easy for users that just copy the default directories to a web server. Users with deviating requirements can still adjust the "low-level" `scale_install_*_repository_url` variables individually...

**Comment by acch** [comment]
I've looked at this again more closely. It appears that whenever we use the variable `scale_install_repository_url` we add the appropriate subdirectory to it:

```yaml
# roles/core/node/tasks/install_repository.yml:
baseurl: "{{ scale_install_repository_url }}gpfs_rpms/"
```
```yaml
# roles/gui/node/tasks/install_repository.yml:
baseurl: "{{ scale_install_repository_url }}/gpfs_rpms/"
```
```yaml
# roles/scale_fileauditlogging/node/tasks/install_repository.yml:
baseurl: "{{ scale_install_repository_url }}{{ scale_fal_url }}"
```

...just to list a few. So it looks like `scale_install_repository_url` already *is* that common variable which you're proposing, all component-specific URLs are derived from that.

Looks like this already addresses your suggestion - or am I missing something here? :thinking:

**Comment by olemyk** [comment]
As you say, this has been implemented after we created the issue. Should we close this?  @acch @rajan-mis

**Comment by rajan-mis** [comment]
Yes we should close this issue. Thanks @olemyk
