### ISSUE TITLE
chef based parity - Set  "automaticMountOption": true by default

### ISSUE THREAD

**Issue by mrolyat** [IBM/ibm-spectrum-scale-install-infra#215]
Should set automaticMountOption to true by default

```"scale_storage":[
    {
      "filesystem": "cesSharedRoot",
      "blockSize": 4M,
      "defaultMetadataReplicas": 1,
      "defaultDataReplicas": 1,
      "automaticMountOption": true,
      "defaultMountPoint": /ibm/cesSharedRoot,
      "disks": [
       {
        "device": "/dev/sde",
        "nsd": "nsd2",
        "servers": "node-vm4",
        "usage": dataAndMetadata,
        "pool": system
       }
      ]
    }

**Comment by rajan-mis** [comment]
@mrolyat I merged this fix in the development_staging branch. i created filesystem without specifying this option in the inventory. 

` -A                 yes                      Automatic mount option`

**Comment by acch** [comment]
Current version on development_staging contains the following:
```yaml
# roles/core/cluster/defaults/main.yml
automaticMountOption: true
```

Hence, file systems will be created with `-A yes` by default. Can this be closed?

**Comment by rajan-mis** [comment]
@mrolyat Can you please verify and close this issue. Thanks
