### ISSUE TITLE
Running the playbook on master branch, on CentOS 7.6, fails at Zimon task

### ISSUE THREAD

**Issue by whowutwut** [IBM/ibm-spectrum-scale-install-infra#22]
I'm not doing anything with Zimon, but it goes into that role from the `playbook.yml` definitions, which is fine.   

Failed here: `- name: install | Find gpfs.collector (gpfs.collector) RPM`

But after some digging.. the cause of this is because `zimon_url` is not defined.  The set_facts right above it is skipped because of the missing test for CentOS.  

https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/master/roles/zimon/node/tasks/install_local_pkg.yml#L100

We seem to have other mentions of CentOS  
```
$ git grep CentOS
roles/core/node/tasks/build.yml:        ansible_distribution == 'CentOS' or
```

Quick fix: 

```diff
(molecule.venv) [root@autogen-centos76-x-master ibm-spectrum-scale-install-infra]# git diff roles/zimon/node/tasks/install_local_pkg.yml
diff --git a/roles/zimon/node/tasks/install_local_pkg.yml b/roles/zimon/node/tasks/install_local_pkg.yml
index 6e10489..59722c3 100644
--- a/roles/zimon/node/tasks/install_local_pkg.yml
+++ b/roles/zimon/node/tasks/install_local_pkg.yml
@@ -100,7 +100,9 @@
 - name: install | zimon path
   set_fact:
     zimon_url: 'zimon_rpms/rhel7/'
-  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
+  when:
+    - ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
+    - ansible_distribution_major_version == '7'

 - name: install | zimon path
   set_fact:
```

With this patch, it does run to completion.   I will try the `dev` branch now.

**Comment by acch** [comment]
Hi @whowutwut, this seems to be an older one - and there have been numerous improvements for CentOS recently (i.e. the platform is now checked against `scale_rhel_distribution`). Would you mind giving this another try on the *development_staging* branch, and if it succeeds close the issue?

Thanks!

**Comment by rajan-mis** [comment]
I am closing this issue.please reopen if anyone is having concern about this issue. we have already merged and tested this fix. thanks
