### ISSUE TITLE
Syntax error in tasks

### ISSUE THREAD

**Issue by azaelRguez** [IBM/ibm-spectrum-scale-install-infra#229]
Can't run the the Ansible Playbook by a syntax error in files:

- roles/gui/cluster/tasks/hasi_vault_user.yml (line 21)

- roles/gui/cluster/tasks/users.yml (line 26)

There is an extra hyphen `-` than cause that issue in Master branch.

**Comment by rajan-mis** [comment]
@azaelRguez Can you please close this issue if its fixed. thanks
