### ISSUE TITLE
Comparison of archive checksum broken

### ISSUE THREAD

**Issue by acch** [IBM/ibm-spectrum-scale-install-infra#261]
Ansible version: 2.9.14
Scale version: 5.0.5.3

The `Compare checksums` task doesn't work:

```
TASK [core/node : install | Compare checksums] *************************************************************************
fatal: [t1-alpha-12]: FAILED! => {"msg": "The conditional check 'scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5' failed. The error was: error while evaluating conditional (scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5): 'dict object' has no attribute 'md5'"}
```

I've tested with the localpkg installation method, but the same code exists in multiple places, so other install methods might be affected, too.

I'll investigate.

**Comment by rajan-mis** [comment]
Thanks @acch . I had also seen this issue. 

https://github.com/IBM/ibm-spectrum-scale-install-infra/issues/90

**Comment by acch** [comment]
The syntax of the `stat` module has changed. #262 should fix this.
