### ISSUE TITLE
Unsupported parameters for (yum) module: disable_excludes...

### ISSUE THREAD

**Issue by azaelRguez** [IBM/ibm-spectrum-scale-install-infra#276]
During the task "core/node : build | Install prereqs for building GPL module from source", I am getting the next message 10 time: `FAILED - RETRYING: build | Install prereqs for building GPL module from source (10 retries left).`

After 10 retires, it show the next error:

```fatal: [supports1]: FAILED! => {"attempts": 10, "changed": false, "msg": "Unsupported parameters for (yum) module: disable_excludes Supported parameters include: allow_downgrade,conf_file,disable_gpg_check,disablerepo,enablerepo,exclude,install_repoquery,installroot,list,name,security,skip_broken,state,update_cache,validate_certs"}```

I'm using a minimal configuration for files: playbook.yml & hosts.

Features:
- RHEL 7.9
- Spectrum_Scale_Advanced-5.0.4.2-x86_64-Linux-install
- Ansible 2.4

**Comment by rajan-mis** [comment]
@azaelRguez Please let me know if you want to fix this issue from your side. Thanks

**Comment by acch** [comment]
`disable_excludes` was introduced with Ansible 2.7 ([link](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-disable_excludes)). According to the README you'd need version 2.9. Can you please try again with Ansible 2.9 and check if the error persists?

**Comment by azaelRguez** [comment]
I was using Ansible 2.7
I no longer present the problem with version 2.9
Thank you!

**Comment by rajan-mis** [comment]
@azaelRguez If you are not hitting this issue , please close this issue.
