### ISSUE TITLE
Building GPL module failed

### ISSUE THREAD

**Issue by azaelRguez** [IBM/ibm-spectrum-scale-install-infra#277]
During the task "core/node : build | Compile GPL module", I'm getting a large error message like this:

```
fatal: [dispirit2]: FAILED! => {"changed": true, "cmd": "export LINUX_DISTRIBUTION=REDHAT_AS_LINUX ; /usr/lpp/mmfs/bin/mmbuildgpl --quiet", "delta": "0:00:06.094036", "end": "2020-10-30 18:54:08.622466", "msg": "non-zero return code", "rc": 1, "start": "2020-10-30 18:54:02.528430", "stderr": "Verifying that tools to build the portability layer exist...
```

I'm using a minimal configuration for files: playbook.yml & hosts.

Features:
- RHEL 7.8
- Spectrum_Scale_Advanced-5.0.4.2-x86_64-Linux-install
- Ansible 2.9

**Comment by aspalazz** [comment]
**Hi Azaeal -** please see [Table 40 in the Spectrum Scale FAQ](https://www.ibm.com/support/knowledgecenter/en/STXKQY/gpfsclustersfaq.html).  

The RHEL 7.8 kernel was not supported in 5.0.4.2.  I'd highly recommend using a more current GA'd level such as 5.0.5.3 or a development level.

**Comment by azaelRguez** [comment]
Thanks!
