### ISSUE TITLE
Generate a default group_vars directory

### ISSUE THREAD

**Issue by mrolyat** [IBM/ibm-spectrum-scale-install-infra#28]
Add required directory structure for ease of use (should this also remove host_vars if no longer required?).

**Comment by whowutwut** [comment]
I guess since we do this for the master branch and `host_vars`  directory... I'll create a PR to address this.

**Comment by rajan-mis** [comment]
@whowutwut I have asked Mike to create this issue . i have already changed and planning to create PR.
