### ISSUE TITLE
Get scale version from gpfs.base if user has not defined for directory method. 

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#29]
`- scale_version: 5.0.4.2`

**Comment by rajan-mis** [comment]
@digvijay2016 @mamuthiah FYI.

**Comment by whowutwut** [comment]
Just curious, what was the intended reason for providing this variable in the first place? Is it being used to compare versions in upgrade?

**Comment by rajan-mis** [comment]
Its not only for upgrade and we are using this during install to build rpm package from specific scale version directory .

**Comment by rajan-mis** [comment]
We have implemented this for directory and local package method.
