### ISSUE TITLE
Scale installation on fyre environment is failing

### ISSUE THREAD

**Issue by bssrikanth** [IBM/ibm-spectrum-scale-install-infra#340]
Issue:
=======
Currently on fyre environment, scale install playbook fails [https://github.ibm.com/Spectrum-Scale-Deployment/fyre-ansible-roles/blob/master/playbooks/install-scale.yml] with error pointed @ https://github.ibm.com/Spectrum-Scale-Deployment/fyre-ansible-roles/issues/109

When I digged in deep I see the condition required to start scale cluster is not met @ roles/core/cluster/tasks/cluster_start.yml. scale_daemon_node_list is empty in our case, since {{ ansible_play_hosts }} does not have attribute `state` which is in the condition that was introduced @ commit https://github.com/IBM/ibm-spectrum-scale-install-infra/commit/6449a133857be8540d4d3b8f4fd1d47f50ed43ac

This issue is to 
1. get more information on commit  https://github.com/IBM/ibm-spectrum-scale-install-infra/commit/6449a133857be8540d4d3b8f4fd1d47f50ed43ac
Under what circumstance {{ ansible_play_hosts }} would have attribute `state` and what are the possible values it can hold other than  `maintenance`.
2. In a environment if state attribute does not exist, then can we skip this check for such environments?

I skipped/commented out the mentioned check, and was able to deploy and start gpfs cluster without manual startup workaround.

Expected result: Users should be able to install,configure and start gpfs cluster on fyre environment without manual intervention.

**Comment by rajan-mis** [comment]
@bssrikanth  Yes we already create PR for this fix but we are discussing about variable( either it should be state or scale_state).

https://github.com/IBM/ibm-spectrum-scale-install-infra/pull/295

Work around:

Just add state: present in the hosts file inventory,

```
[cluster01]
host-vm1 scale_cluster_quorum=true   scale_cluster_manager=true scale_cluster_gui=false state=present
```


Looks like fyre still using hosts and group vars inventory but if we will use JSON inventory then we will not see this problem because we are always setting `state=present` in the JSON inventory for every node.

**Comment by bssrikanth** [comment]
Sure thank you @rajan-mis 
I have a request on commit messages: having more information in the commit message on the changes done would be useful, so that any users looking at commits would get an idea on why the change was introduced and what are the different values would the newly introduced attribute could posses.

**Comment by rajan-mis** [comment]
@bssrikanth Thank you. This state variable was mainly added for spectrum scale AWS cloud offering.  

Current state refers to following but this is not integrated for all supported component, 

  `state: present`  ( by default for new cluster creation or adding a new node into existing cluster)
  `state: absent `  ( remove a node from cluster but this is not yet officially supported , 
                             this is only getting supported with AWS cloud offering with complete work flow)
 ` state: maintenance` ( ansible role will not try to start gpfs daemon if node is having state as maintenance)

**Comment by rajan-mis** [comment]
We merge this fix PR today. now need to set state variable.  Thanks

**Comment by rajan-mis** [comment]
Please validate and close this issue.

**Comment by rajan-mis** [comment]
I am closing this issue for now. please reopen if you are still seeing this issue.
