### ISSUE TITLE
Enable provision to set NSD usage via scale_clusterdefinition.json

### ISSUE THREAD

**Issue by sasikeda** [IBM/ibm-spectrum-scale-install-infra#59]
mmcrnsd stanza file format;

```
%nsd: device=DiskName
  nsd=NsdName
  servers=ServerList
  usage={dataOnly | metadataOnly | dataAndMetadata | descOnly | localCache}
  failureGroup=FailureGroup
  pool=StoragePool
```

Cloud architecture requires to create "descOnly" NSD for failture group balancing and NVME local drives, requires "localCache". Currently, scale_clusterdefintion.json lacks a parameter to distinguish NSD usage.

**Comment by rajan-mis** [comment]
@sasikeda Thanks.  @digvijay2016 and I discussed  for this requirement and Digvijay is planning to add `usage` parameter in the automated cloud JSON creation code then Ansible playbook will automatically add this in nsd stanza file while nsd creation. I have verified by manually adding `usage` parameter in the scale_clusterdefintion.json . Thanks

**Comment by sasikeda** [comment]
@rajan-mis thank you. 
@digvijay2016 can you share the sample of where are you planning to add "usage" parameter in the json ?

**Comment by digvijay2016** [comment]
`    "scale_storage": [
        {
            "filesystem": "fs1",
            "blockSize": "1M",
            "defaultMetadataReplicas": 1,
            "defaultDataReplicas": 1,
            "disks": [
                {
                    "device": "/dev/xvdf",
                    "servers": "ip-10-0-27-132",
                    "nsd": "nsd1"
                },
                {
                    "device": "/dev/xvdf",
                    "servers": "ip-10-0-39-76",
                    "nsd": "nsd2"
                },
                {
                    "device": "/dev/xvdf",
                    "servers": "ip-10-0-20-240",
                    "nsd": "nsd3",
                    **"usage": "descOnly"**
                 }
            ]
        }
    ]`

**Comment by rajan-mis** [comment]
@digvijay2016 @sasikeda Can we close this issue. Thanks

**Comment by sasikeda** [comment]
Thanks @rajan-mis @digvijay2016 for working on this. Sure, please go ahead for closure.
