### ISSUE TITLE
"Spectrum Scale" to “Storage Scale” in the README update

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#686]
**Is your feature request related to a problem? Please describe.**
"Spectrum Scale" to “Storage Scale” in the README update

**Describe the solution you'd like**
"Spectrum Scale" to “Storage Scale” in the README update

**Comment by acch** [comment]
#693 fixes this.

Please ignore / delete #691 and #692 ...
