### ISSUE TITLE
stat.md5 broken in Ansible 2.9.x and this option is removed and deprecated from Ansible 2.9.x

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#90]
stat.md5 broken in Ansible 2.9.x and this option is removed and deprecated from Ansible 2.9.x

TASK [core/node : install | Compare checksums] ```
************************************************************************************************************************************
fatal: [test-vm1]: FAILED! => {"msg": "The conditional check 'scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5' failed. The error was: error while evaluating conditional (scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5): 'dict object' has no attribute 'md5'"}
```

**Comment by whowutwut** [comment]
@rajan-mis 👍  I also hit this 5 days ago when I happened to place the md5 file into the same location...  

My notes
 
---------

3. Downlaoded the 5.0.5.0 Scale Advanced, but also created an .md5  file in /root, so we hit this.... 
```
TASK [core/node : install | Compare checksums] ******************************************************************************************
fatal: [jdun-rtp-master]: FAILED! => {"msg": "The conditional check 'scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5' failed. The error was: error while evaluating conditional (scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5): 'dict object' has no attribute 'md5'"}
```

Seem to match, but OK.... let me delete it... 
```
# md5sum Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install
ae75cf323d58025170b2dd012a4ee481  Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install
# cat Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install.md5
ae75cf323d58025170b2dd012a4ee481  Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install
# rm Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install.md5
rm: remove regular file ‘Spectrum_Scale_Advanced-5.0.5.0-x86_64-Linux-install.md5’? y
```

-------


 How would we know to report this as an error?

**Comment by rajan-mis** [comment]
@whowutwut  Mark has seen this issue in cloud deployment environment when he kept both md5 and  SEPackage build in the same directory  then i asked him to move md5 package from local directory path to proceed with the deployment and he is able proceed .  but then we realized this optio  n i.e md5  is already removed from ansible 2.9.5 version .  now we have a option to include checksum but i see checksum of md5 package and regular package is comming different .

**Comment by acch** [comment]
The syntax of the `stat` module has changed. #262 should fix this.

**Comment by acch** [comment]
Closing this issue as #262 was already merged.
