### ISSUE TITLE
Unable to install data access edition with repository install

### ISSUE THREAD

**Issue by lahdete** [IBM/ibm-spectrum-scale-install-infra#92]
Please add control for data access license also.
gpfs.license.da
missing from here:
roles/core/node/tasks/install_license_repository.yml

**Comment by rajan-mis** [comment]
@lahdete Thanks for reporting this issue . we will add this fix with next commit . thanks

**Comment by rajan-mis** [comment]
@lahdete You can try with local package method i.e  `scale_install_localpkg_path`  method , it should work with all supported license package.

**Comment by rajan-mis** [comment]
This issue got fixed .

**Comment by rajan-mis** [comment]
@lahdete Can you please close this issue. Thanks
